name: Deploy OSRSEvent Server to ECR and ECS

on:
  push:
    branches: [ master ]
    paths:
      'server/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
  
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition osrsevents-task-def --query taskDefinition > task-definition.json
      
    - name: Deploy image to ECR
      uses: kciter/aws-ecr-action@v4
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ID }}
        repo: osrsevents-server
        tags: latest,${{ github.sha }}
        region: us-east-2
        dockerfile: ./server/Dockerfile
        path: ./server
      
    - name: Update ECS Task Definition
      id: render-server-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: osrsevents-image-latest
        image: 867327836252.dkr.ecr.us-east-2.amazonaws.com/osrsevents-server
        environment-variables: "LOG_LEVEL=info"

    - name: Deploy ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-server-container.outputs.task-definition }}
        service: osrs-service
        cluster: osrs-events-cluster

# 
        
