name: Deploy OSRSEvent Server to ECR

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy Server Backend
      uses: kciter/aws-ecr-action@v4
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: 867327836252
        repo: osrsevents
        tags: server-latest
        region: us-east-2
        dockerfile: ./server/Dockerfile
        path: ./server
        
    - name: Deploy Client Frontend
      uses: kciter/aws-ecr-action@v4
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: 867327836252
        repo: osrsevents
        tags: client-latest
        region: us-east-2
        dockerfile: ./web/Dockerfile
        path: ./web
